spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orvalmap
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Met à jour le schéma sans supprimer les données existantes
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.orvalmap: DEBUG
    org.springframework.security: DEBUG
