spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orvalmap
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create # ⚠️ Temporaire : Recrée les tables pour ajouter les nouvelles colonnes
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  cloudinary:
    name: dcrwgoet6 # REMPLACEZ PAR VOTRE VRAI CLOUD NAME LOCAL
    key: 938263175175197     # REMPLACEZ PAR VOTRE VRAIE CLÉ API LOCALE
    secret: bq_GpAu2TTmd0Bynljq1XKVPBLc # REMPLACEZ PAR VOTRE VRAI SECRET API LOCAL

logging:
  level:
    com.orvalmap: DEBUG
    org.springframework.security: DEBUG
