spring:
  application:
    name: orval-map
  profiles:
    active: dev # Profil par défaut en local

# Configuration commune à tous les environnements
cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}

jwt:
  secret: ${JWT_SECRET:cleSecreteAChangerQuiDoitQdMemeetreSuperGrande}

server:
  address: 0.0.0.0
  port: ${PORT:8080} # Railway injecte la variable PORT automatiquement

logging:
  level:
    com.orvalmap: INFO
    org.springframework.security: INFO
