spring:
  application:
    name: orval-map
  
  datasource:
    # Ces noms sont les standards de Spring Boot. 
    # Ils seront écrasés si vous définissez SPRING_DATASOURCE_URL dans Railway.
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/orvalmap}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}

jwt:
  secret: ${JWT_SECRET:cleSecreteAChangerQuiDoitQdMemeetreSuperGrandeEtSecurisee}

server:
  port: ${PORT:8080}
