spring.application.name=orval-map

# --- Configuration PostgreSQL ---
# En PROD : On definira les variables d'environnement DB_URL, DB_USER, DB_PASSWORD
# En LOCAL : Il utilisera les valeurs par defaut (apres les deux points :)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/orvalmap}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:password}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# --- Configuration Cloudinary ---
# En PROD : Vous definirez CLOUDINARY_CLOUD_NAME, etc. dans l'interface de votre hebergeur
# En LOCAL : Remplacez les valeurs par defaut ci-dessous ou configurez votre IDE
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME:votre_cloud_name_ici}
cloudinary.api_key=${CLOUDINARY_API_KEY:votre_api_key_ici}
cloudinary.api_secret=${CLOUDINARY_API_SECRET:votre_api_secret_ici}

# --- Securite JWT ---
# En PROD : Il FAUT definir une variable JWT_SECRET tres longue et aleatoire
jwt.secret=${JWT_SECRET:cleSecreteAChangerQuiDoitQdMemeetreSuperGrande}

server.address=0.0.0.0
logging.level.com.orvalmap.security=DEBUG
logging.level.org.springframework.security=DEBUG
spring.profiles.active=dev
